### ISSUE TITLE
Doen not kill child process if killed

### ISSUE THREAD

**Issue by mikegleasonjr** [githubnemo/CompileDaemon#12]
If I kill `CompileDaemon`, it does not kill the child process started with `-command=…`

**Comment by githubnemo** [comment]
Test case:

`test/wait.go`:

```
package main

import (
	"time"
)

func main() {
	time.Sleep(5 * time.Minute)
}
```

Terminal 1:

    $ CompileDaemon -directory=test -build 'go build wait.go' -command './test/wait'

Terminal 2:

    $ pgrep wait
    3701
    $ kill $(pgrep CompileDaemon)
    $ pgrep wait
    3701

Expected: `pgrep wait` does not return a PID.

**Comment by githubnemo** [comment]
This is quite inconvenient to fix since `SIGTERM` is not catched by `signal.Notify(c, os.Kill)`.

Maybe later.

**Comment by tomj74** [comment]
This orphaned-child behavior is also present for SIGINT:
```
$ pgrep wait
3701
$ kill -s INT $(pgrep CompileDaemon)
$ pgrep wait
3701
```

submitted a PR to at least address the interrupt case.

**Comment by githubnemo** [comment]
Should be fixed now thanks to @tomj74.
