### ISSUE TITLE
Seems to break Atom?

### ISSUE THREAD

**Issue by ChrisCooney** [githubnemo/CompileDaemon#19]
I've managed to start up the CompileDaemon with minimal effort. It seems to work great!

If I make a change in Atom and then hit save, the CompileDaemon does it thing and rebuild/restart. The problem is, Atom immediately freezes as soon as this happens. Is this something you've observed?

**Comment by githubnemo** [comment]
No, I haven't observed this but I don't use Atom on a daily basis.

How exactly are you starting CompileDaemon?

**Comment by ChrisCooney** [comment]
Running the binary from the bin directory of my Go workspace. As soon as the reload happens, Atom locks up.

I tested this with IntelliJ and didn't get the same behaviour. I suspect there's some cross over in functionality?

**Comment by githubnemo** [comment]
I cannot help you if you don't provide more information, for example how you are invoking CompileDaemon.

**Comment by githubnemo** [comment]
Closing due to lack of feedback and reproducability.
