### ISSUE TITLE
Goal of project

### ISSUE THREAD

**Issue by itsjamie** [githubnemo/CompileDaemon#20]
I was attempting to make this fit an existing project that currently used reflex to watch for changes and Makefile targets after using this on some personal projects and loving the simplicity, and I realized that I wanted to perform different actions if different sets of files changed.

Example:
*.tmpl - `go generate path/views/templates` which executes `go-bindata` for those templates
*.scss - `go generate path/views/styles` which executes sass->css compilation, then `go-bindata` for the CSS

Is it a goal of the project to support this type of conditional targeting? Reading the README, I'd lean towards no, but wanted to check.

**Comment by githubnemo** [comment]
Why not have two instances of the daemon watch over your project?
