### ISSUE TITLE
Command to run and test at the same time

### ISSUE THREAD

**Issue by lesterzone** [githubnemo/CompileDaemon#21]
First: Thank you.

After reading documentation and options, I can't `run` and `test` at the same time.
I think that could be possible with this package since most of the time we (devs) need it.

Currently:

```sh
#!/bin/sh
CompileDaemon \
    -directory=. \
    -recursive=true \
    -build="go build -o server" \
    -command="./server -port=4000 -host=localhost" \
    -color=true
```

What I'm looking:

```sh
#!/bin/sh
CompileDaemon \
    -directory=. \
    -recursive=true \
    -build="go build -o server" \
    -command="./server -port=4000 -host=localhost && go test ./... " \
    -color=true
```

Sorry If I missed something from docs.
Thank you for your time.

**Comment by githubnemo** [comment]
You can already do that, for example with

    -command='/bin/sh -c "./server -port 4000 -host=localhost && go test ./..."'

but maybe I am missing something?

**Comment by lesterzone** [comment]
I get:
`stderr: &&: 1: &&: Syntax error: Unterminated quoted string`
but... that's because of the string.

For tests, until I fix string issue:

load.sh

```sh
#!/bin/sh
go test ./... && ./server
```

start.sh
```sh
#!/bin/sh
CompileDaemon \
    -directory=. \
    -recursive=true \
    -build="go build -o server" \
    -command='./load.sh'
    -color=true
```

Works!.
We can close this now.

Thank you.
