### ISSUE TITLE
fsnotify dependency resolves to empty fsnofity repo on github

### ISSUE THREAD

**Issue by CameronAckermanSEL** [githubnemo/CompileDaemon#30]
As of two hours ago there's now an empty fsnotify repo on github that compile daemon resolves to as its dependency.
http://gopkg.in/fsnotify.v1 -> https://github.com/go-fsnotify/fsnotify

This smells of a package injection attack but it seems to not have materialized.

At the very least, this has broken CompileDaemon because it resolves to the wrong dependency.

The maintainers of gopkg.in will probably figure it out, but we thought we'd let you know :)

**Comment by githubnemo** [comment]
Thanks for reporting. Changed the import to the new URL.
