### ISSUE TITLE
2019/09/25 12:04:06 stderr: fuser: Invalid option --server_address

### ISSUE THREAD

**Issue by hamidabdul1994** [githubnemo/CompileDaemon#37]
I wanted to run two command , But i gives error.

**CompileDaemon -command="fuser 50052/tcp && go run main.go --server_address :50052"**

If you have port closing option kindly please help

**Comment by githubnemo** [comment]
Can you show me the error you are getting?

**Comment by hamidabdul1994** [comment]
2019/09/25 14:48:20 stderr: Specified file name && does not exist.
2019/09/25 14:48:20 stderr: Specified file name go does not exist.
2019/09/25 14:48:20 stderr: Specified file name run does not exist.
2019/09/25 14:48:20 stderr: fuser: Invalid option --server_address
2019/09/25 14:48:20 stderr: Usage: fuser [-fIMuvw] [-a|-s] [-4|-6] [-c|-m|-n SPACE]
2019/09/25 14:48:20 stderr:              [-k [-i] [-SIGNAL]] NAME...
2019/09/25 14:48:20 stderr:        fuser -l
2019/09/25 14:48:20 stderr:        fuser -V
2019/09/25 14:48:20 stderr: Show which processes use the named files, sockets, or filesystems.
2019/09/25 14:48:20 stderr: 
2019/09/25 14:48:20 stderr:   -a,--all              display unused files too
2019/09/25 14:48:20 stderr:   -i,--interactive      ask before killing (ignored without -k)
2019/09/25 14:48:20 stderr:   -I,--inode            use always inodes to compare files
2019/09/25 14:48:20 stderr:   -k,--kill             kill processes accessing the named file
2019/09/25 14:48:20 stderr:   -l,--list-signals     list available signal names
2019/09/25 14:48:20 stderr:   -m,--mount            show all processes using the named filesystems or
2019/09/25 14:48:20 stderr:                         block device
2019/09/25 14:48:20 stderr:   -M,--ismountpoint     fulfill request only if NAME is a mount point
2019/09/25 14:48:20 stderr:   -n,--namespace SPACE  search in this name space (file, udp, or tcp)
2019/09/25 14:48:20 stderr:   -s,--silent           silent operation
2019/09/25 14:48:20 stderr:   -SIGNAL               send this signal instead of SIGKILL
2019/09/25 14:48:20 stderr:   -u,--user             display user IDs
2019/09/25 14:48:20 stderr:   -v,--verbose          verbose output
2019/09/25 14:48:20 stderr:   -w,--writeonly        kill only processes with write access
2019/09/25 14:48:20 stderr:   -V,--version          display version information
2019/09/25 14:48:20 stderr:   -4,--ipv4             search IPv4 sockets only
2019/09/25 14:48:20 stderr:   -6,--ipv6             search IPv6 sockets only
2019/09/25 14:48:20 stderr:   -                     reset options
2019/09/25 14:48:20 stderr: 
2019/09/25 14:48:20 stderr:   udp/tcp names: [local_port][,[rmt_host][,[rmt_port]]]

**Comment by hamidabdul1994** [comment]
> I wanted to run two command , But i gives error.
> 
> **CompileDaemon -command="fuser 50052/tcp && go run main.go --server_address :50052"**
> 
> If you have port closing option kindly please help

**Comment by githubnemo** [comment]
The error was that CompileDaemon does not support (ba)sh command chaining. You have to run it in a shell or as a script.

For example:

    CompileDaemon -command='/bin/sh -c "fuser 50052/tcp && go run main.go --server_address :50052"'
