### ISSUE TITLE
Allow option to NOT build

### ISSUE THREAD

**Issue by J7mbo** [githubnemo/CompileDaemon#43]
This is great to just have `go run .` re-run on a file change. It's perfect with the combination of a templating engine which rebuilds go files once the html files are updated.

However, CompileDaemon always compiles the binary when many times I only want to have go run executed with -command.

Is there any chance of providing an option to not build?

**Comment by J7mbo** [comment]
I switched to [reflex](https://github.com/cespare/reflex) and I can run:

> reflex --start-service --regex='.*.go)' go run .

I will close this issue, but please feel free to reopen it if you consider the idea valuable. Thanks!

**Comment by pjebs** [comment]
See https://github.com/githubnemo/CompileDaemon/issues/54
