### ISSUE TITLE
CompileDaemon not found

### ISSUE THREAD

**Issue by dapobelieve** [githubnemo/CompileDaemon#45]
I get the error "CompileDaemon: not found" and I don't understand why I'm getting such error

**Comment by terev** [comment]
@dapobelieve in what context? Is that an error from the binary or the os when trying to run it? Please paste the command you were trying to run

**Comment by dapobelieve** [comment]
From my docker container @terev

**Comment by dapobelieve** [comment]
<img width="732" alt="Screenshot 2020-02-23 at 4 25 04 PM" src="https://user-images.githubusercontent.com/15062380/75114762-16092e80-5659-11ea-999b-d9cbf818e1f6.png">
This is my simple dockerfile and I still get `CompileDaemon: not found` when i run dockercompose

**Comment by terev** [comment]
@dapobelieve you specified the entrypoint as CompileDaemon which overrides the default entrypoint which is usually a shell with PATH set. if you changed your entrypoint to
```
ENTRYPOINT ["/go/bin/CompileDaemon", ...]
```
it should work

**Comment by dapobelieve** [comment]
Ok I'll try that

**Comment by dapobelieve** [comment]
Still doesn't work. How are other users able to use it? I just don't get it at all

**Comment by terev** [comment]
@dapobelieve go get installs into GOPATH . whatever GOPATH is in your base image is where it'll be installed. it could be a different dir than /go/bin

**Comment by terev** [comment]
@dapobelieve what base image are you using in your FROM ?

**Comment by dapobelieve** [comment]
Thanks @terev finally set it up properly had to do alot of reading

**Comment by terev** [comment]
@dapobelieve np . glad you got it working eventually

**Comment by feuangel** [comment]
> Gracias @terev finalmente lo configuró correctamente tuve que leer mucho

Y como lo resolviste?
me está pasando lo mismo.
Gracias

**Comment by terev** [comment]
@feuangel your entrypoint needs to reference the absolute path to the executable. Or if the base image you're building off of has a shell as the entrypoint and GOPATH/bin is in PATH you should be able to specify `CMD ["CompileDaemon", ...]` instead overriding the entrypoint

**Comment by PhuSanh** [comment]
hi @dapobelieve, I encounter the same issue, could you share your solution, thanks

**Comment by githubnemo** [comment]
@PhuSanh there is no general solution to this as it depends on your Dockerfile. Can you share it?

**Comment by rituparnakhaund** [comment]
@githubnemo how do I find what is the gopath for your base image?

**Comment by WiRight** [comment]
In my case I getting error on golang:1.18.2-alpine3.15 image

Downgrade to golang:1.16.0-alpine3.13 works for me

Try it

**Comment by ostenbom** [comment]
Rather than downgrading (we're on 1.18), switching the installation method to `go install -mod=mod github.com/githubnemo/CompileDaemon` worked for me!

**Comment by Jatin-Kamboj** [comment]
> Rather than downgrading (we're on 1.18), switching the installation method to `go install -mod=mod github.com/githubnemo/CompileDaemon` worked for me!

This worked for me

**Comment by sumonbiswas2010** [comment]
> go install -mod=mod github.com/githubnemo/CompileDaemon

Worked for me also. Thanks man!
