### ISSUE TITLE
multiple build commands

### ISSUE THREAD

**Issue by pjebs** [githubnemo/CompileDaemon#54]
It would be great if multiple build commands could be run when file changes are detected:

```
1. docker build -t
2. docker-compose down
3. docker-compose up
```

**Comment by githubnemo** [comment]
Just write a shell script and execute it instead:

`CompileDaemon -command "bash build.sh"`

build.sh:

```bash
docker build -t
docker-compose down
docker-compose up
```

**Comment by pjebs** [comment]
This technique seems to still build go app: `go build ...`.

My docker process already does the building

**Comment by githubnemo** [comment]
Sorry, I meant to write `-build="bash build.sh"`. Edited my original comment.

**Comment by pjebs** [comment]
following your edited advice, I was losing the standard out messages from `docker-compose up`.

My workaround was:

```
CompileDaemon  -command "bash build.sh" -build="echo 'building'"
```

**Comment by pjebs** [comment]
Thanks

**Comment by pjebs** [comment]
Does this work on WIndows? It doesn't seem to work for my colleague?
