### ISSUE TITLE
"CompileDaemon": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by Denes-cilwal** [githubnemo/CompileDaemon#78]
![Screen Shot 2022-04-25 at 16 03 40](https://user-images.githubusercontent.com/67893343/165071138-2d0047ee-70a2-4978-b881-8059e1a9b101.png)
Faced this issue when running docker 
Any solution on this ?

**Comment by Denes-cilwal** [comment]
The issue has been solved

**Comment by mervanerdem** [comment]
What was the solition
